COLUMNS:
  Type: object
  Days_for_shipment_scheduled: int64
  Late_delivery_risk: int64
  Customer_Country: object
  Customer_Segment: object
  Order_Country: object
  Order_Item_Discount_Rate: float64
  Order_Item_Quantity: int64
  Sales: float64
  Order_Status: object
  Product_Name: object
  Product_Price: float64
  Shipping_Mode: object
  order_date_year: int64
  order_date_month: int64
  order_date_day: int64

TARGET_COLUMN:
  name: Late_delivery_risk