artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/SanjuShusanth/ML-Projects/raw/main/Supplychain.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Supplychain.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  train_data_path: artifacts/data_validation/train.csv
  test_data_path: artifacts/data_validation/test.csv


data_transformation:
  root_dir: artifacts/data_transformation
  preprocessor_path: artifacts/models/preprocessor.pkl
  train_data_path: artifacts/data_validation/train.csv
  test_data_path: artifacts/data_validation/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/trans_train.csv
  test_data_path: artifacts/data_transformation/trans_test.csv
  model_path: artifacts/models/model.pkl
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/trans_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json



