artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/SanjuShusanth/ML-Projects/raw/main/Raw.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Raw.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  train_data_path: artifacts/data_validation/train.csv
  test_data_path: artifacts/data_validation/test.csv



